server:
  port: 8187
  tomcat:
    threads:
      max: 200
      min-spare: 50
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flash
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    web: trace
    ru:
      lomov:
        flashbackend: warn
