
export const GET_POST_LIST_REQUEST = 'GET_POST_LIST_REQUEST';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE';

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_FAILURE = 'GET_POST_BY_ID_FAILURE';

export const GET_POST_DETAIL_REQUEST = 'GET_POST_DETAIL_REQUEST';
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
export const GET_POST_DETAIL_FAILURE = 'GET_POST_DETAIL_FAILURE';

export const GET_POST_COMMENT_LIST_REQUEST = 'GET_POST_COMMENT_LIST_REQUEST';
export const GET_POST_COMMENT_LIST_SUCCESS = 'GET_POST_COMMENT_LIST_SUCCESS';
export const GET_POST_COMMENT_LIST_FAILURE = 'GET_POST_COMMENT_LIST_FAILURE';

export const ADD_POST_COMMENT_REQUEST = 'ADD_POST_COMMENT_REQUEST';
export const ADD_POST_COMMENT_SUCCESS = 'ADD_POST_COMMENT_SUCCESS';
export const ADD_POST_COMMENT_FAILURE = 'ADD_POST_COMMENT_FAILURE';

export const DELETE_POST_COMMENT_REQUEST = 'DELETE_POST_COMMENT_REQUEST';
export const DELETE_POST_COMMENT_SUCCESS = 'DELETE_POST_COMMENT_SUCCESS';
export const DELETE_POST_COMMENT_FAILURE = 'DELETE_POST_COMMENT_FAILURE';

export const EDIT_POST_COMMENT_REQUEST = 'EDIT_POST_COMMENT_REQUEST';
export const EDIT_POST_COMMENT_SUCCESS = 'EDIT_POST_COMMENT_SUCCESS';
export const EDIT_POST_COMMENT_FAILURE = 'EDIT_POST_COMMENT_FAILURE';


export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';

export const USER_LIKE_POST_REQUEST = 'USER_LIKE_POST_REQUEST';
export const USER_LIKE_POST_SUCCESS = 'USER_LIKE_POST_SUCCESS';
export const USER_LIKE_POST_FAILURE = 'USER_LIKE_POST_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const GET_POST_LIST_BY_USER_REQUEST = 'GET_POST_LIST_BY_USER_REQUEST';
export const GET_POST_LIST_BY_USER_SUCCESS = 'GET_POST_LIST_BY_USER_SUCCESS';
export const GET_POST_LIST_BY_USER_FAILURE = 'GET_POST_LIST_BY_USER_FAILURE';

export const GET_POST_LIST_BY_TAG_REQUEST = 'GET_POST_LIST_BY_TAG_REQUEST';
export const GET_POST_LIST_BY_TAG_SUCCESS = 'GET_POST_LIST_BY_TAG_SUCCESS';
export const GET_POST_LIST_BY_TAG_FAILURE = 'GET_POST_LIST_BY_TAG_FAILURE';

export const GET_POST_LIST_BY_CATEGORY_REQUEST = 'GET_POST_LIST_BY_CATEGORY_REQUEST';
export const GET_POST_LIST_BY_CATEGORY_SUCCESS = 'GET_POST_LIST_BY_CATEGORY_SUCCESS';
export const GET_POST_LIST_BY_CATEGORY_FAILURE = 'GET_POST_LIST_BY_CATEGORY_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_REQUEST = 'GET_POST_LIST_BY_KEYWORD_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_FAILURE = 'GET_POST_LIST_BY_KEYWORD_FAILURE';

export const REPOST_POST_REQUEST = 'REPOST_POST_REQUEST';
export const REPOST_POST_SUCCESS = 'REPOST_POST_SUCCESS';
export const REPOST_POST_FAILURE = 'REPOST_POST_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_CATEGORY_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_TAG_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_TAG_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_TAG_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_TAG_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_TAG_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_TAG_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_USER_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_USER_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_USER_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_USER_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_TAG_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_FAILURE';

export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_REQUEST = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_REQUEST';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_SUCCESS = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_SUCCESS';
export const GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_FAILURE = 'GET_POST_LIST_BY_KEYWORD_AND_USER_AND_CATEGORY_AND_TAG_AND_KEYWORD_FAILURE';