package ru.lomov.flashbackend.dto;

import lombok.Data;
import ru.lomov.flashbackend.entities.Post;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Data
public class PostDto {
    private Long postId;
    private Long userId;
    private String content;
    private Set<String> mediaUrls = new HashSet<>();
    private Set<String> hashtags = new HashSet<>();
    private Set<Long> mentionedUserIds = new HashSet<>();
    private String visibility;
    private boolean commentsEnabled;
    private boolean likesEnabled;
    private boolean sharingEnabled;
    private boolean isPinned;
    private boolean isArchived;
    private String status;
    private String location;
    private Double latitude;
    private Double longitude;
    private String language;
    private String sentiment;
    private Double sentimentScore;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime scheduledAt;
    private LocalDateTime publishedAt;
    private int likeCount;
    private int commentCount;
    private int shareCount;
    private int viewCount;
    private int saveCount;
    private boolean isSponsored;
    private String sponsorId;
    private String campaignId;
    private Double cpmRate;
    private Double revenueGenerated;
    private String metaTitle;
    private String metaDescription;
    private Set<String> keywords = new HashSet<>();
    private String ogImage;
    private String canonicalUrl;
    private boolean isModerated;
    private LocalDateTime moderatedAt;
    private String moderationStatus;
    private String moderationReason;
    private Double moderationScore;
    private int version;
    private Long originalPostId;
    private String postType;
    private Set<String> pollOptions = new HashSet<>();
    private Set<Integer> pollVotes = new HashSet<>();
    private LocalDateTime pollEndsAt;
    private String streamUrl;
    private String streamKey;
    private Boolean isLive;
    private Integer liveViewers;
    private LocalDateTime liveStartedAt;
    private LocalDateTime liveEndedAt;
    private String deviceInfo;
    private String appVersion;
    private String ipAddress;
    private String userAgent;

    // Constructor to convert from Post entity
    public PostDto(Post post) {
        this.postId = post.getPostId();
        this.userId = post.getUserId();
        this.content = post.getContent();
        this.mediaUrls = post.getMediaUrls();
        this.hashtags = post.getHashtags();
        this.mentionedUserIds = post.getMentionedUserIds();
        this.visibility = post.getVisibility();
        this.commentsEnabled = post.isCommentsEnabled();
        this.likesEnabled = post.isLikesEnabled();
        this.sharingEnabled = post.isSharingEnabled();
        this.isPinned = post.isPinned();
        this.isArchived = post.isArchived();
        this.status = post.getStatus();
        this.location = post.getLocation();
        this.latitude = post.getLatitude();
        this.longitude = post.getLongitude();
        this.language = post.getLanguage();
        this.sentiment = post.getSentiment();
        this.sentimentScore = post.getSentimentScore();
        this.createdAt = post.getCreatedAt();
        this.updatedAt = post.getUpdatedAt();
        this.scheduledAt = post.getScheduledAt();
        this.publishedAt = post.getPublishedAt();
        this.likeCount = post.getLikeCount();
        this.commentCount = post.getCommentCount();
        this.shareCount = post.getShareCount();
        this.viewCount = post.getViewCount();
        this.saveCount = post.getSaveCount();
        this.isSponsored = post.isSponsored();
        this.sponsorId = post.getSponsorId();
        this.campaignId = post.getCampaignId();
        this.cpmRate = post.getCpmRate();
        this.revenueGenerated = post.getRevenueGenerated();
        this.metaTitle = post.getMetaTitle();
        this.metaDescription = post.getMetaDescription();
        this.keywords = post.getKeywords();
        this.ogImage = post.getOgImage();
        this.canonicalUrl = post.getCanonicalUrl();
        this.isModerated = post.isModerated();
        this.moderatedAt = post.getModeratedAt();
        this.moderationStatus = post.getModerationStatus();
        this.moderationReason = post.getModerationReason();
        this.moderationScore = post.getModerationScore();
        this.version = post.getVersion();
        this.originalPostId = post.getOriginalPostId();
        this.postType = post.getPostType();
        this.pollOptions = post.getPollOptions();
        this.pollVotes = post.getPollVotes();
        this.pollEndsAt = post.getPollEndsAt();
        this.streamUrl = post.getStreamUrl();
        this.streamKey = post.getStreamKey();
        this.isLive = post.getIsLive();
        this.liveViewers = post.getLiveViewers();
        this.liveStartedAt = post.getLiveStartedAt();
        this.liveEndedAt = post.getLiveEndedAt();
        this.deviceInfo = post.getDeviceInfo();
        this.appVersion = post.getAppVersion();
        this.ipAddress = post.getIpAddress();
        this.userAgent = post.getUserAgent();
    }
}
